Update the deterministic dependencies, as the build is failing in PyInstaller on MacOS and it looks like some conflict with setuptools and distutils, message: 'AttributeError: 'Distribution' object has no attribute 'convert_2to3_doctests''